### PR TITLE
postman-json to postman

### PR DESCRIPTION
**Pull request by bitsol**
I overheard @dvdsgl [talking about this](https://quicktype.slack.com/archives/C68E91E8J/p1521860054000020) on Slack:

> @mark can we change `-s postman-json` to `-s postman`?

...So I went ahead and switched the names.

### CODE REVIEW

**Comment by dvdsgl** [comment]
Thank you! Please also change here:

https://github.com/quicktype/quicktype/blob/2b9f385dacfec0ed74412dcc8ce940c42e3b0230/src/cli/index.ts#L309

**Comment by bitsol** [comment]
Done @dvdsgl.

**Comment by bitsol** [comment]
Uh oh. I should have used a separate branch for those last three commits. What can I do @schani @dvdsgl?

**Comment by schani** [comment]
@bitsol Would you mind making a separate pull request for the `postman-json` change?

If you need help with Git, ask us on Slack.

**Comment by bitsol** [comment]
Closed for now.

**Pull request closed without merging**
