### PR TITLE
Update Ruby integer to Types::Integer (#1125)

### LINKED ISSUE #1125: Ruby code generation: Latest dry-types breaks Types::Int
When code generating from JSON::Schema to Ruby, quicktype uses dry-types's `Types::Int` for integers. However, since [version 0.13.0](https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md#v0130-2018-05-03), they introduced a breaking change by renaming this to `Types::Integer`. 

Please change the Ruby codegen to use `Types::Integer` instead.

### PR DESCRIPTION
**Pull request by dugsmith**
Fixes #1125

### CODE REVIEW

**Comment by schani** [comment]
@dugsmith Thank you!  How far backwards compatible is this?

**Comment by dugsmith** [comment]
@schani It is only compatible with version [this version of dry-types](https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md#v0130-2018-05-03) or greater, as of May 3, 2018.

**Comment by schani** [comment]
I see - it breaks Ruby in CI.

Could you make this into an option?  See [here](https://github.com/quicktype/quicktype/blob/master/src/quicktype-core/language/ruby/index.ts#L45).  If you make the new way the default then you'll have to set CI to set the option for the old way [here](https://github.com/quicktype/quicktype/blob/master/test/languages.ts#L292).

**Comment by dvdsgl** [comment]
Perhaps we just need to update the DRY gem?

**Comment by schani** [comment]
@dvdsgl I don't know the Ruby community, but I bet there'll be lots of people for who this will break their setup, and we can't ask them to update a package.

**Comment by dugsmith** [comment]
@schani @dvdsgl I expect most of the Ruby community will be willing to update this package. Being a breaking change, any newcomers to quicktype, like me, will find it broken from the beginning if we don't resolve it. 

Alternatively, you could refactor quicktype to not use dry-types at all, but I think that would be a step backwards.

**Comment by schani** [comment]
@dugsmith If you insist, then please modify the `Dockerfile` to use the new package so we don't break CI.  See the bottom of the [README](https://github.com/quicktype/quicktype) on how to test.

**Comment by dugsmith** [comment]
@schani I modified the Gemfile.lock with the latest versions of all the Ruby dependencies and pushed that. I don't have time to pull the environment and test locally, so hopefully that'll work. If not, it's not the end of the world, it can wait until I or someone has more time to devote to it.

**Comment by schani** [comment]
This is the error we're getting now.  Is there another `Int` that you didn't convert to `Integer`?

```
bundler: failed to load command: main.rb (main.rb)
  |  
  | NameError: uninitialized constant #<Module:0x000000014f5ac8>::Int
  | /app/test/runs/ruby-155135/TopLevel.rb:18:in `<module:Types>'
  | /app/test/runs/ruby-155135/TopLevel.rb:15:in `<top (required)>'
  | main.rb:4:in `require'
  | main.rb:4:in `<top (required)>'
  |  
  | Command failed
  | {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug790.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-155135"
  | }
  | Could not run command for JSON output
  | {
  | "error": {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug790.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-155135"
  | },
  | "cwd": "/app/test/runs/ruby-155135"
  | }
  | Fixture threw an exception
  | {
  | "error": {
  | "error": {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug790.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-155135"
  | },
  | "cwd": "/app/test/runs/ruby-155135"
  | },
  | "sample": {
  | "path": "test/inputs/json/priority/bug790.json",
  | "additionalRendererOptions": {},
  | "saveOutput": true
  | },
  | "cwd": "/app/test/runs/ruby-155135"
  | }
  | [object Object]
  | at /app/test/test.ts:68:17
  | at step (/app/test/test.ts:32:23)
  | at Object.throw (/app/test/test.ts:13:53)
  | at rejected (/app/test/test.ts:5:65)
  | at <anonymous>
  | bundler: failed to load command: main.rb (main.rb)
  |  
  | NameError: uninitialized constant #<Module:0x00000001011868>::Int
  | /app/test/runs/ruby-d91e5d/TopLevel.rb:18:in `<module:Types>'
  | /app/test/runs/ruby-d91e5d/TopLevel.rb:15:in `<top (required)>'
  | main.rb:4:in `require'
  | main.rb:4:in `<top (required)>'
  |  
  | Command failed
  | {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug863.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-d91e5d"
  | }
  | Could not run command for JSON output
  | {
  | "error": {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug863.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-d91e5d"
  | },
  | "cwd": "/app/test/runs/ruby-d91e5d"
  | }
  | Fixture threw an exception
  | npm{
  | "error": {
  | "error": {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug863.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-d91e5d"
  | },
  | "cwd": "/app/test/runs/ruby-d91e5d"
  | },
  | "sample": {
  | "path": "test/inputs/json/priority/bug863.json",
  | "additionalRendererOptions": {},
  | "saveOutput": true
  | },
  | "cwd": "/app/test/runs/ruby-d91e5d"
  | }
```

**Comment by dugsmith** [comment]
Well, that seemed to make it worse. :-( Maybe we should just drop this until someone has more time to pull down the image and work through the issues.

**Comment by schani** [comment]
@dugsmith Same error - seems like there's still some `Int` left.  The other thing is a sporadic failure due to .NET crashing.

```
bundler: failed to load command: main.rb (main.rb)
  |  
  | NameError: uninitialized constant #<Module:0x00000001db4178>::Int
  | /app/test/runs/ruby-e6eeeb/TopLevel.rb:18:in `<module:Types>'
  | /app/test/runs/ruby-e6eeeb/TopLevel.rb:15:in `<top (required)>'
  | main.rb:4:in `require'
  | main.rb:4:in `<top (required)>'
  |  
  | Command failed
  | {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug790.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-e6eeeb"
  | }
  | Could not run command for JSON output
  | {
  | "error": {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug790.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-e6eeeb"
  | },
  | "cwd": "/app/test/runs/ruby-e6eeeb"
  | }
  | Fixture threw an exception
  | {
  | "error": {
  | "error": {
  | "command": "bundle exec main.rb \"/app/test/inputs/json/priority/bug790.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/ruby-e6eeeb"
  | },
  | "cwd": "/app/test/runs/ruby-e6eeeb"
  | },
  | "sample": {
  | "path": "test/inputs/json/priority/bug790.json",
  | "additionalRendererOptions": {},
  | "saveOutput": true
  | },
  | "cwd": "/app/test/runs/ruby-e6eeeb"
  | }
  | [object Object]
  | at /app/test/test.ts:68:17
  | at step (/app/test/test.ts:32:23)
  | at Object.throw (/app/test/test.ts:13:53)
  | at rejected (/app/test/test.ts:5:65)
  | at <anonymous>
```

**Comment by schani** [comment]
@dugsmith What's the status on this?

**Comment by dugsmith** [comment]
@schani, I'm sorry, I don't have time to work on this further, and we are postponing our use of quicktype for the forseeable future anyway. I thought it would be a "quick" change, but it turns out that I'd need to pull the code and take more time. If nobody else wants to take this from here, feel free to close it.

**Comment by dvdsgl** [comment]
Superseded by #1385

**Pull request closed without merging**
