### PR TITLE
Add support for Java Records (JEP 395)

### LINKED ISSUE #2019: Add support for Java Records (JEP 395)
Please support Java Records as an alternative output mode (similar to "Use lombok").

Java 16 introduced Java Records:

- JEP 395: Records – https://openjdk.org/jeps/395
- https://www.baeldung.com/java-record-keyword

The welcome example from https://app.quicktype.io/ should output

```java
package io.quicktype;

public record Welcome (
    String greeting,
    String[] instructions) {
}
```

The multiple JSON example should output

```java
// Album.java

package io.quicktype;

public record Album (
    String name,
    Artist artist,
    Track[] tracks) {
}

// Artist.java

package io.quicktype;

public record Artist (
    String name,
    long founded,
    String[] members) {
}

// Track.java

package io.quicktype;

public record Track (
    String name,
    long duration) {
}
```

Thank you for maintaining this great tool!

### PR DESCRIPTION
**Pull request by simon04**
Fixes #2019.

cc: @dvdsgl

### CODE REVIEW

**Comment by dvdsgl** [comment]
@simon04 the `java-record` fixture is now running in CI but it fails. Please take a look.

**Comment by simon04** [comment]
@dvdsgl, thanks for enabling CI. I've modified .github/workflows/test-pr.yaml to use Azul Zulu OpenJDK 17 LTS (instead of AdoptOpenJDK 11) since Java 11 is too old to test Java Records (JEP 395). I think you need to approve the workflow modification before the CI may run. Thanks!

**Comment by dvdsgl** [comment]
@simon04 great! Thank you. I approved, there are some more errors it seems.

**Comment by dvdsgl** [comment]
@simon04 sorry, but please reopen! For some reason, this was automerged by GitHub even though Java fixtures are still failing.

**Pull request merged**
