### PR TITLE
Dart null safty and fix for freeze

### PR DESCRIPTION
**Pull request by stha-ums**
Following are the things I worked on:

- added detect enum option 
- added null-safety
- make all properties nullable 
- keep properties name, enum, and union name same as Key in JSON (this is useful while generated for Freezed with JsonSerializer) .

I have done manual testing. So it should be working. For automatic testing. I do not have enough knowledge. Is anyone can test or guide me. That would be great.

### CODE REVIEW

**Comment by NatoBoram** [comment]
Fixes #1673 #1711 #1723 #1729 #1737 #1739 #1741 #1744

**Comment by schani** [comment]
@stha-ums Thank you for this contribution!  There's a lot of reformatting of unrelated files in this PR, as well as huge changes to `package-lock.json`.  It also breaks the Elm tests - why does it touch Elm at all?

**Comment by NatoBoram** [comment]
@schani Looks like someone on your team misused the `package.json` file by manually entering/ordering dependencies instead of using `npm`. The dependencies in `package.json` are generally in the same order to avoid this kind of formatting issue.

As for `elm-package.json`, is it an auto-generated file? This project includes `prettier`. If someone uses this project's settings, it is reasonable that prettier would be applied.

**Comment by stha-ums** [comment]
@schani  there was an error while building that project with elm versioning so I had to change the version to run on my machine. I have relatively new to Node, what do you suggest for the resolution?

**Comment by NatoBoram** [comment]
@stha-ums Can you edit this PR to keep their original config, even if it doesn't build on your machine? It's clear they don't have much time to give to this project, so if it works on their machine I think it's good enough.

**Comment by stha-ums** [comment]
sent another PR #1764 .

**Pull request closed without merging**
