### PR TITLE
Typescript lang: handle additional properties

### LINKED ISSUE #1615: AdditionalProperties ignored for Typescript definition generation
Thanks for the amazing work done in this library !
I'm struggling a bit with `additionalProperties` JSON-schema property.
As stated from the documentation:

> The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword. **By default any additional properties are allowed.**

So, not defining `additionalProperties` is equivalent to `"additionalProperties": true`

However, given the following JSON-schema

```json
{
    "type": "object",
    "properties": {
        "a": { "type": "string" }
    },
    "required": ["a"]
}
```

the generated Typescript definition is

```ts
export interface MyObject {
    a: string;
}
```

while I was expecting

```ts
export interface MyObject {
    a: string;
    [key: string]: unknown;
}
```

I tried setting `"additionalProperties": true` and even `"additionalProperties": { type: "string" }`, without any success. **It looks  like `additionalProperties` does not have any impact on generated Typescript definition.**
You can access my latest test at https://app.quicktype.io?share=Y4Y07xZGS9zncuWpEtSt

Any advice on how to proceed with this issue ? Happy to help with a PR if pointed in the right direction :)

### PR DESCRIPTION
**Pull request by ReneWerner87**
this pull request closes #1615

### CODE REVIEW

**Comment by ReneWerner87** [comment]
hi what can i do to progress this pull request?

**Comment by ReneWerner87** [comment]
@schani @dvdsgl 
hi have been waiting for a few days now, have I forgotten anything ? 
am very interested in this feature going into the master and thus next version

**Comment by dvdsgl** [comment]
Hi @ReneWerner87! Can you please fix the PR to only include relevant changes?

**Comment by ReneWerner87** [comment]
depends on what changes you mean, but can gladly reverse the changes to the package json again

here is a list of the reasons for the changes to the files:
TypeScriptFlow.test.ts -> tests for the feature
TypeScriptFlow.ts -> the changes for the feature
package-lock.json + package.json -> fix a problem 
image
image
with 0.19
image
image

**Comment by ReneWerner87** [comment]
@dvdsgl the revert of the package.json changes -> https://github.com/quicktype/quicktype/pull/2029/commits/23069c49c6a8979acb00373f46f5e1e6c38358c0

**Comment by ReneWerner87** [comment]
@dvdsgl & @schani how can i progress the pull request ?

**Comment by george-haroun** [comment]
Could you please test & merge this PR soon

**Comment by dvdsgl** [comment]
Taking a look now.

**Pull request merged**
