### PR TITLE
Kotlin Support

### PR DESCRIPTION
**Pull request by dvdsgl**
- [x] Get fixture running in Docker
- [x] Refactor enums
- [x] Support empty classes when `--framework none`
- [x] Support unions
- [x] Support top-level non-objects

### CODE REVIEW

**Comment by dvdsgl** [comment]
Must fix this upstream: https://github.com/cbeust/klaxon/issues/145

**Comment by schani** [comment]
Does this bug affect all unions?

**Comment by dvdsgl** [comment]
No, I think it is a general bug affecting `List<List<T>>` where `T` requires custom conversion (enums, unions).

**Comment by schani** [comment]
I see.  Is there maybe some other list/vector/array type we can use that makes it work?

**Comment by dvdsgl** [comment]
I tried switching to `Array` and got the same error.

**Pull request merged**
