### PR TITLE
Corrects optional class properties in Python

### PR DESCRIPTION
**Pull request by thatsokay**
Stops serialising missing optional types from Python as `None`.

- Preserves `isOptional` property in type graph for Python
- Emits `None` check for optional types in Python `to_dict` method

Implements #1391 except no changes to Python's `supportsOptionalClassProperties`, `PythonRenderer.pythonType`, or `from_dict`.

### CODE REVIEW

**Comment by dvdsgl** [comment]
It looks like this created a test failure in a non-Python language:https://buildkite.com/typeguard/quicktype-pr/builds/1403#ae6f2d7d-7fa0-4f61-b017-8f73402f7c5c/206-5260

**Comment by thatsokay** [comment]
Fixed the JS prop types tests. Still looking at the Python tests.

**Comment by thatsokay** [comment]
The Python tests are failing on `json/priority/combinations{1,2,3,4}.json` and `schema/direct-union.1.json` when there is a type of `{optional?: null}`. Without this PR, the Python serializer would always produce `{optional: null}` but with the PR it produces `{}`. Neither is really correct but this PR could break for anyone with such a type.

**Comment by thatsokay** [comment]
Fixed tests

**Comment by thatsokay** [comment]
@dvdsgl @schani would you be able to look at the diff test to check if it looks ok?

**Comment by dvdsgl** [comment]
Diff looks good to me but @schani will have to review the changes.

**Comment by maximeCony** [comment]
@schani I know this is an old PR but any chance you give it a look? :pray: 

Is there anything I can do to push this to the finish line?

**Comment by maximeCony** [comment]
Thank you! 🙏

**Pull request merged**
