### PR TITLE
Fix #1356: Just Types Kotlin generator creates invalid capitalization

### LINKED ISSUE #1356: Just Types Kotlin generator creates invalid capitalization
See following example:

image

Note that original Json states `Id` while generated variable is `ID`. This causes parsing to fail.

### PR DESCRIPTION
**Pull request by pt2121**
When using Kotlin with no framework, capitalizing acronyms could cause parsing issues.

### CODE REVIEW

**Comment by dvdsgl** [comment]
Great and thank you! Please rebase, we have just fixed our CI.

**Comment by pt2121** [comment]
✔️ done. Thanks

**Comment by dvdsgl** [comment]
This will break existing code, so we will have to coordinate with a version increase.

**Comment by pt2121** [comment]
Yeah, this is a breaking change. When will you plan to bump a major version?

**Comment by dvdsgl** [comment]
@pt2121 Our CI is working now. Happy to work with you to get this merged if you can take a look at build error.

**Comment by pt2121** [comment]
I probably can take a look at this over the weekend.

**Comment by dvdsgl** [comment]
Please reopen if you plan to take another crack at this. Thanks!

**Comment by pt2121** [comment]
Just took another look, it looks like the issue was partially addressed by #1991 so we don't need this change anymore.

**Comment by dvdsgl** [comment]
Thanks @pt2121 !

**Pull request closed without merging**
