### PR TITLE
languages: add cjson converter

### PR DESCRIPTION
**Pull request by joelguittet**
This pull request add a new language converter to have support of cJSON (https://github.com/DaveGamble/cJSON), a well known C library to parse and print json using C language. CJSON library is used on Linux and on MCU (integrated in ESP-IDF to use famous ESP32 for example) .

The options are similar to c++ generator (but simplified), and the comment at the top of the CJSON.ts file indicate how to start easily.

### CODE REVIEW

**Comment by dvdsgl** [comment]
@joelguittet this is amazing! Can you share a sample of the code generated? Also, we will need to add a test fixture–is this something you can attempt?

**Comment by joelguittet** [comment]
Hello @dvdsgl 

Thanks for your enthusiasm! Yes sure, I was trying to generate again after rebasing because I have worked with old version of nodejs so it's in the process to be available soon I hope.

> Also, we will need to add a test fixture–is this something you can attempt?

Do you mean integration in the pipeline, test-pr.yaml ? Yes it's something I want to add at the same time too :-)

Two questions please:
- it seems somebody need to validate something because the PR indicate "1 workflow awaiting approval". What is it ?
- In the deep source Javascript results, some issues may be difficult to fix, which kind of issues are mandatory to solve ?

Joel

**Comment by joelguittet** [comment]
So here is an example of the cJSON fiel generated from https://github.com/quicktype/quicktype/blob/master/test/inputs/schema/description.schema:

```
/**
 * description.h
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

#ifndef __DESCRIPTION_H__
#define __DESCRIPTION_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <cJSON.h>

#ifndef cJSON_Bool
#define cJSON_Bool (cJSON_True | cJSON_False)
#endif

/**
 * An enumeration
 */
enum Enum {
    ENUM_BAR,
    ENUM_FOO,
};

/**
 * Either a number or a string
 */
struct Union {
    int type;
    union {
        double number;
        char * string;
    } value;
};

struct ObjectOrStringClass {
    /**
     * This must not get lost
     */
    double prop;
};

struct ObjectOrStringUnion {
    int type;
    union {
        char * string;
        struct ObjectOrStringClass * object_or_string_class;
    } value;
};

/**
 * The top-level class.
 * Its description has two lines.
 */
struct Description {
    /**
     * A pretty boolean
     */
    bool * bar;
    /**
     * An enumeration
     */
    enum Enum description_enum;
    double * foo;
    struct ObjectOrStringUnion object_or_string;
    /**
     * Either a number or a string
     */
    struct Union description_union;
};

enum Enum cJSON_GetEnumValue(const cJSON * j);
cJSON * cJSON_CreateEnum(const enum Enum x);

struct Union cJSON_GetUnionValue(const cJSON * j);
cJSON * cJSON_CreateUnion(const struct Union x);
void cJSON_ReleaseUnion(struct Union * x);
void cJSON_DeleteUnion(struct Union * x);

struct ObjectOrStringUnion cJSON_GetObjectOrStringUnionValue(const cJSON * j);
cJSON * cJSON_CreateObjectOrStringUnion(const struct ObjectOrStringUnion x);
void cJSON_ReleaseObjectOrStringUnion(struct ObjectOrStringUnion * x);
void cJSON_DeleteObjectOrStringUnion(struct ObjectOrStringUnion * x);

struct ObjectOrStringClass * cJSON_ParseObjectOrStringClass(const char * s);
struct ObjectOrStringClass * cJSON_GetObjectOrStringClassValue(const cJSON * j);
cJSON * cJSON_CreateObjectOrStringClass(const struct ObjectOrStringClass * x);
char * cJSON_PrintObjectOrStringClass(const struct ObjectOrStringClass * x);
void cJSON_ReleaseObjectOrStringClass(struct ObjectOrStringClass * x);
void cJSON_DeleteObjectOrStringClass(struct ObjectOrStringClass * x);

struct Description * cJSON_ParseDescription(const char * s);
struct Description * cJSON_GetDescriptionValue(const cJSON * j);
cJSON * cJSON_CreateDescription(const struct Description * x);
char * cJSON_PrintDescription(const struct Description * x);
void cJSON_ReleaseDescription(struct Description * x);
void cJSON_DeleteDescription(struct Description * x);

enum Enum cJSON_GetEnumValue(const cJSON * j) {
    enum Enum x = 0;
    if (!strcmp(cJSON_GetStringValue(j), "bar")) x = ENUM_BAR;
    else if (!strcmp(cJSON_GetStringValue(j), "foo")) x = ENUM_FOO;
    return x;
}

cJSON * cJSON_CreateEnum(const enum Enum x) {
    cJSON * j = NULL;
    switch (x) {
        case ENUM_BAR: j = cJSON_CreateString("bar"); break;
        case ENUM_FOO: j = cJSON_CreateString("foo"); break;
    }
    return j;
}

struct Union cJSON_GetUnionValue(const cJSON * j) {
    struct Union x;
    memset(&x, 0, sizeof(struct Union));
    if (cJSON_IsNumber(j)) {
        x.type = cJSON_Number;
        x.value.number = cJSON_GetNumberValue(j);
    }
    else if (cJSON_IsString(j)) {
        x.type = cJSON_String;
        x.value.string = strdup(cJSON_GetStringValue(j));
    }
    return x;
}

cJSON * cJSON_CreateUnion(const struct Union x) {
    cJSON * j = NULL;
    switch (x.type) {
        case cJSON_Number: j = cJSON_CreateNumber(x.value.number); break;
        case cJSON_String: j = cJSON_CreateString(x.value.string); break;
    }
    return j;
}

void cJSON_ReleaseUnion(struct Union * x) {
    if (NULL != x) {
        switch (x->type) {
            case cJSON_String: cJSON_free(x->value.string); break;
        }
        memset(x, 0, sizeof(struct Union));
    }
}

void cJSON_DeleteUnion(struct Union * x) {
    if (NULL != x) {
        cJSON_ReleaseUnion(x);
        cJSON_free(x);
    }
}

struct ObjectOrStringUnion cJSON_GetObjectOrStringUnionValue(const cJSON * j) {
    struct ObjectOrStringUnion x;
    memset(&x, 0, sizeof(struct ObjectOrStringUnion));
    if (cJSON_IsString(j)) {
        x.type = cJSON_String;
        x.value.string = strdup(cJSON_GetStringValue(j));
    }
    else if (cJSON_IsObject(j)) {
        x.type = cJSON_Object;
        x.value.object_or_string_class = cJSON_GetObjectOrStringClassValue(j);
    }
    return x;
}

cJSON * cJSON_CreateObjectOrStringUnion(const struct ObjectOrStringUnion x) {
    cJSON * j = NULL;
    switch (x.type) {
        case cJSON_String: j = cJSON_CreateString(x.value.string); break;
        case cJSON_Object: j = cJSON_CreateObjectOrStringClass(x.value.object_or_string_class); break;
    }
    return j;
}

void cJSON_ReleaseObjectOrStringUnion(struct ObjectOrStringUnion * x) {
    if (NULL != x) {
        switch (x->type) {
            case cJSON_String: cJSON_free(x->value.string); break;
            case cJSON_Object: cJSON_DeleteObjectOrStringClass(x->value.object_or_string_class); break;
        }
        memset(x, 0, sizeof(struct ObjectOrStringUnion));
    }
}

void cJSON_DeleteObjectOrStringUnion(struct ObjectOrStringUnion * x) {
    if (NULL != x) {
        cJSON_ReleaseObjectOrStringUnion(x);
        cJSON_free(x);
    }
}

struct ObjectOrStringClass * cJSON_ParseObjectOrStringClass(const char * s) {
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            struct ObjectOrStringClass * tmp = cJSON_GetObjectOrStringClassValue(j);
            cJSON_Delete(j);
            return tmp;
        }
    }
    return NULL;
}

struct ObjectOrStringClass * cJSON_GetObjectOrStringClassValue(const cJSON * j) {
    struct ObjectOrStringClass * x = cJSON_malloc(sizeof(struct ObjectOrStringClass));
    if (NULL != x) {
        memset(x, 0, sizeof(struct ObjectOrStringClass));
        if (cJSON_HasObjectItem(j, "prop")) {
            x->prop = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "prop"));
        }
    }
    return x;
}

cJSON * cJSON_CreateObjectOrStringClass(const struct ObjectOrStringClass * x) {
    cJSON * j = cJSON_CreateObject();
    if ((NULL != j) && (NULL != x)) {
        cJSON_AddNumberToObject(j, "prop", x->prop);
    }
    return j;
}

char * cJSON_PrintObjectOrStringClass(const struct ObjectOrStringClass * x) {
    if (NULL != x) {
        cJSON * j = cJSON_CreateObjectOrStringClass(x);
        if (NULL != j) {
            char * tmp = cJSON_Print(j);
            cJSON_Delete(j);
            return tmp;
        }
    }
    return NULL;
}

void cJSON_ReleaseObjectOrStringClass(struct ObjectOrStringClass * x) {
    if (NULL != x) {
        memset(x, 0, sizeof(struct ObjectOrStringClass));
    }
}

void cJSON_DeleteObjectOrStringClass(struct ObjectOrStringClass * x) {
    if (NULL != x) {
        cJSON_ReleaseObjectOrStringClass(x);
        cJSON_free(x);
    }
}

struct Description * cJSON_ParseDescription(const char * s) {
    if (NULL != s) {
        cJSON * j = cJSON_Parse(s);
        if (NULL != j) {
            struct Description * tmp = cJSON_GetDescriptionValue(j);
            cJSON_Delete(j);
            return tmp;
        }
    }
    return NULL;
}

struct Description * cJSON_GetDescriptionValue(const cJSON * j) {
    struct Description * x = cJSON_malloc(sizeof(struct Description));
    if (NULL != x) {
        memset(x, 0, sizeof(struct Description));
        if (cJSON_HasObjectItem(j, "bar")) {
            if (NULL != (x->bar = cJSON_malloc(sizeof(bool)))) {
                *x->bar = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "bar"));
            }
        }
        if (cJSON_HasObjectItem(j, "description_enum")) {
            x->description_enum = cJSON_GetEnumValue(cJSON_GetObjectItemCaseSensitive(j, "description_enum"));
        }
        if (cJSON_HasObjectItem(j, "foo")) {
            if (NULL != (x->foo = cJSON_malloc(sizeof(double)))) {
                *x->foo = cJSON_GetNumberValue(cJSON_GetObjectItemCaseSensitive(j, "foo"));
            }
        }
        if (cJSON_HasObjectItem(j, "object_or_string")) {
            x->object_or_string = cJSON_GetObjectOrStringUnionValue(cJSON_GetObjectItemCaseSensitive(j, "object_or_string"));
        }
        if (cJSON_HasObjectItem(j, "description_union")) {
            x->description_union = cJSON_GetUnionValue(cJSON_GetObjectItemCaseSensitive(j, "description_union"));
        }
    }
    return x;
}

cJSON * cJSON_CreateDescription(const struct Description * x) {
    cJSON * j = cJSON_CreateObject();
    if ((NULL != j) && (NULL != x)) {
        if (NULL != x->bar) {
            cJSON_AddBoolToObject(j, "bar", *x->bar);
        }
        cJSON_AddItemToObject(j, "description_enum", cJSON_CreateEnum(x->description_enum));
        if (NULL != x->foo) {
            cJSON_AddNumberToObject(j, "foo", *x->foo);
        }
        cJSON_AddItemToObject(j, "object_or_string", cJSON_CreateObjectOrStringUnion(x->object_or_string));
        cJSON_AddItemToObject(j, "description_union", cJSON_CreateUnion(x->description_union));
    }
    return j;
}

char * cJSON_PrintDescription(const struct Description * x) {
    if (NULL != x) {
        cJSON * j = cJSON_CreateDescription(x);
        if (NULL != j) {
            char * tmp = cJSON_Print(j);
            cJSON_Delete(j);
            return tmp;
        }
    }
    return NULL;
}

void cJSON_ReleaseDescription(struct Description * x) {
    if (NULL != x) {
        if (NULL != x->bar) {
            cJSON_free(x->bar);
        }
        if (NULL != x->foo) {
            cJSON_free(x->foo);
        }
        cJSON_ReleaseObjectOrStringUnion(&x->object_or_string);
        cJSON_ReleaseUnion(&x->description_union);
        memset(x, 0, sizeof(struct Description));
    }
}

void cJSON_DeleteDescription(struct Description * x) {
    if (NULL != x) {
        cJSON_ReleaseDescription(x);
        cJSON_free(x);
    }
}

#ifdef __cplusplus
}
#endif

#endif /* __DESCRIPTION_H__ */
```

**Comment by joelguittet** [comment]
Working on testing, somes fixes in progress.

**Comment by joelguittet** [comment]
@dvdsgl this is now ready for review. I have updated workflow config to get the testing of the new langage.
It seems it need to be approved by a maintainer to be executed. I will be able to check after that, but it's already properly executed on my side.
Thanks,
Joel

**Comment by dvdsgl** [comment]
@joelguittet this is excellent work. Please see CI errors.

**Comment by joelguittet** [comment]
Much more checks and errors to fix, will do it soon and then re-push.

**Comment by joelguittet** [comment]
Finally! It's passing the CI :-)
Some use cases are not addressed and they are clearly mentioned in the language.ts file that skip the corresponding examples schema/json files.
@dvdsgl this is ready for review. The API with the quicktype framework is not very easy to use, this will be my general feedback, but maybe this is also because the C is typed language and I need to define everything.
By the way, this is a first working version of the converter that is ready for most projects!
Hope this will be useful to plenty of people like me manipulating large json in C.
Joel

**Comment by dvdsgl** [comment]
@joelguittet thank you! It should be on app.quicktype.io in a couple of days

**Comment by joelguittet** [comment]
Great thanks!

**Pull request merged**
