### PR TITLE
Typescript zod

### PR DESCRIPTION
**Pull request by ryoid**
Made some fixes from #1771

There are 2 main issues I noticed so far
- When comparing diff via schema, the key that is used for the name of types is different. Seems to be first occurrence for schema, last for JSON (`0cffa.json`)
- Generated schemas sometimes references types that are defined after (`spotify-album.json`)
- Also, properly handling top-level arrays

Not sure how to address these problems, skipped these tests for now. Might look into it when I have time, but would appreciate any help.

### CODE REVIEW

**Comment by dvdsgl** [comment]
@ryoid thank you! Please see build error.

**Comment by ryoid** [comment]
> @ryoid thank you! Please see build error.

Updated!

**Comment by dvdsgl** [comment]
Thank you @ryoid and @Southclaws !

**Comment by Southclaws** [comment]
Oh this is awesome to see, thanks for finishing off what I started!

**Comment by kriswest** [comment]
> Generated schemas sometimes references types that are defined after (spotify-album.json)

They do indeed! https://github.com/glideapps/quicktype/issues/2414

**Pull request merged**
