### PR TITLE
[Dart] Add missing output @JsonKey output for @freezed option

### PR DESCRIPTION
**Pull request by kvnxiao**
Dart language enhancements:

* Resolves missing `@JsonKey()` for `--use-freezed` option https://github.com/quicktype/quicktype/issues/2162 https://github.com/quicktype/quicktype/issues/2339 
* Consructors generated with `--use-json-annotation` or `--use-freezed` will respect the `required` keyword even if the type is considered nullable (we forgot to check if the prop was not optional!).
  * `!prop.isOptional` checks if the var has been explicitly defined as non-nullable
* Fixes `--use-freezed` option always assuming everything is nullable and appending `?` to the end of the type -- this should now be covered by the `required` check, plus the `?` was already factored in by the Dart prop type to begin with.
* Suppress comment tutorial on how to use the generated functions, when `--coders-in-class` is being used, since these top-level functions do not apply anymore
* Remove `json_annotation` import if `--use-freezed` is being used, since the freeze annotations import already provides json_annotation annotations.

Excerpts:

`./script/quicktype --src-lang schema generated_freezed.json -l dart --use-json-annotation --use-freezed --coders-in-class`
`generated_freezed.json`
```json
{
    "$id": "datamodel",
    "$schema": "https://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/DocumentType",
    "definitions": {
        "DocumentType": {
            "title": "DocumentType",
            "type": "object",
            "required": ["time_created"],
            "properties": {
                "time_created": {
                    "type": ["string", "null"],
                    "format": "date-time"
                }
            }
        }
    }
}
```

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'document_type.freezed.dart';
part 'document_type.g.dart';

@freezed
class DocumentType with _$DocumentType {
    const factory DocumentType({
        @JsonKey(name: "time_created")
        required DateTime? timeCreated,
    }) = _DocumentType;

    factory DocumentType.fromJson(Map<String, dynamic> json) => _$DocumentTypeFromJson(json);
}
```

Notice that `time_created` is nullable, but also specified as required in the JSON Schema, and this is properly reflected in the generated code.

### CODE REVIEW

**Comment by kvnxiao** [comment]
Hi @dvdsgl ! 

May I kindly also request for this to be reviewed and for a new build to be released so that we may use these fixes in production without having to run our local fork?

Thank you!

**Comment by dvdsgl** [comment]
It should have been released immediately.

**Comment by kvnxiao** [comment]
Thanks! Let me know if there's any changes needed for this PR to be merged.

**Comment by kvnxiao** [comment]
Hi @dvdsgl , apologies for the ping again but would you have some time to review this PR for this to get merged?

Thank you!

**Comment by dvdsgl** [comment]
Thank you!

**Review by abinvs-2019 — COMMENTED** [review]
LGTM

**Pull request merged**
