### PR TITLE
Add acronym style option for kotlin

### PR DESCRIPTION
**Pull request by kathewang**
This change adds the acronym style to the CLI for kotlin for the just-types framework. This follows same pattern as swift acronym style option.

### CODE REVIEW

**Comment by kathewang** [comment]
@schani Would you be able to review this?

**Comment by kathewang** [comment]
Or @dvdsgl? I'm also not sure why the build hasn't run yet

**Comment by schani** [comment]
Could you please increment the minor versions of `quicktype-core` and the main `quicktype` package?  I'll merge it then.

**Comment by kathewang** [comment]
@schani done

**Comment by kathewang** [comment]
@schani Is there something wrong with the build here? When would the new npm package be published?

**Comment by kathewang** [comment]
Thank you @schani!

**Pull request merged**
