### PR TITLE
C++: Emit to_json/from_json helpers in the correct namespace

### LINKED ISSUE #1024: C++ code generated by quicktype does not compile in Visual Studio 2017 when "conformance mode" is off
I have generated C++ code from JSON Schema "Coordinate" and tried compiling it with VS 15.7.6. It turned out that if you set "Conformance mode" to "No", it doesn't compile. I have attached the sample project and a screenshot of the said option.
The error is as follows:

```
1>------ Build started: Project: quicktype_compilation, Configuration: Debug Win32 ------
1>stdafx.cpp
1>quicktype_compilation.cpp
1>s:\quicktype_compilation\quicktype_compilation\vd_json_serializer.h(18): error C2679: binary '=': no operator found which takes a right-hand operand of type 'double' (or there is no acceptable conversion)
...
```
You can see it yourself when compiling my project.

[quicktype_compilation.zip](https://github.com/quicktype/quicktype/files/2273880/quicktype_compilation.zip)
image

### PR DESCRIPTION
**Pull request by louiswins**
Right now quicktype emits `to_json` and `from_json` customizations in the `nlohmann` namespace. This is incorrect (although it happens to work with some compilers in some configurations depending on which methods you call). The correct approach is to emit the helpers in the _user code's_ namespace, e.g. the `quicktype` namespace in the default configuration.

#1109 attempted to fix this, but that PR took the approach of putting these functions in the `nlohmann::detail` namespace, which is even worse! (See https://github.com/nlohmann/json/discussions/3280#discussioncomment-2937051)

Here are some choices I made during this PR that I'd like feedback on since I'm not very familiar with this project's conventions:
- I unilaterally changed the namespace instead of adding an option. I thought this was appropriate because the old generated code is simply incorrect, but I am willing to hide this behind a new option.
- I removed the `msbuildPermissive` option entirely for similar reasons. I can put it back if this is a back-compat problem.

Additionally, the code now emits
```c++
namespace quicktype {
    /* type definitions */
}

namespace quicktype {
    /* to_json and from_json declarations & definitions */
}
```
with redundant close/open of the namespace. Fixing this would be a bigger change than I am comfortable making with my limited understanding of the quicktype code.

Fixes #1024, #1185, #1333, #1494 (and maybe others).

### CODE REVIEW

**Comment by dvdsgl** [comment]
@louiswins thank you. Our test suite is now running again, apologies for the delay.

Can you check out the build errors? It looks like the `ourQualifier` type signature is mismatched.

**Comment by dvdsgl** [comment]
@louiswins build now passes, but there are errors in tests.

To run locally, do:

```shell
$ FIXTURE=cplusplus,schema-cplusplus npm test
```

**Comment by dvdsgl** [comment]
@louiswins would love to get this passing tests, but I don't know C++. Please reopen if you have some time!

**Comment by louiswins** [comment]
Thanks for taking a look! And for getting the test suite running, this will make things a lot easier.

It looks like the problem is that now `boost::variant` deserializers are being emitted in the `quicktype` namespace so they aren't being found by [ADL](https://en.cppreference.com/w/cpp/language/adl). They need to be a specialization of `nlohmann::adl_serializer` instead (like is currently done for `std::shared_ptr<T>`). I hadn't tested with any variants so I didn't come across this earlier.

I'll look into it but it may take a while, so I'll leave this PR closed for now.

**Comment by louiswins** [comment]
Actually I did get a chance to look at this today. Thanks again for fixing the build, I'm not sure what happened there. But I've got all the the tests passing now.

I don't think I can reopen this PR myself. @dvdsgl can you reopen it? Thanks for all your help!

**Pull request merged**
