### PR TITLE
Add descriptions for EnumOption

### PR DESCRIPTION
**Pull request by schani**

### CODE REVIEW

**Comment by schani** [comment]
@bitsol Have you looked at this?  This is in reference to #889

**Comment by schani** [comment]
@bitsol Are you still interested in this?

**Comment by bitsol** [comment]
Sorry @schani; I'm really busy.
What needs to be done?

**Comment by schani** [comment]
@bitsol The display names which this PR adds internally would have to be printed in the CLI help, like you requested in your issue.

**Comment by bitsol** [comment]
Where are language specific options passed to the CLI?

**Comment by schani** [comment]
What you need is the part where renderer options are "translated" to `--help` output, which is [here](https://github.com/quicktype/quicktype/blob/master/src/cli/index.ts#L604).

**Comment by schani** [comment]
It's this package:

```
const getUsage = require("command-line-usage");
```

**Pull request closed without merging**
