### PR TITLE
FIxed #1180. Added optional string to emmited dart model file which

### LINKED ISSUE #1180: Generated Dart class, toJson() Method produces invalid Json
Problem

### PR DESCRIPTION
**Pull request by prachil007**
will generate valid Json from dart toJson() method.

### CODE REVIEW

**Comment by schani** [comment]
Thank you for your PR!  Unfortunately it introduces a bug - our CI fails here:

```
One is not an object at path .encrust.Hibernia.
  | Error: Output is not equivalent to input.
  | {
  | "expectedFile": "/app/test/inputs/json/priority/combinations1.json",
```

You can run the testsuite on your machine with `FIXTURE=dart npm test`

**Comment by prachil007** [comment]
Hey @schani,

Thanks for the actual error. I`m on it. Will push the new code once I test it properly.

**Comment by prachil007** [comment]
Hello @schani

I am trying to set up docker on my machine(win 10), it keeps crashing. I have tried two different versions without success

Is there any other way that I can run full tests?

Basically it clears the npm tests, but does not pass through the scripts folder.

**Comment by dvdsgl** [comment]
Tests fail. Please reopen if you can take a look at fixing them!

**Pull request closed without merging**
