### PR TITLE
Add member constraints for double to cpp

### PR DESCRIPTION
**Pull request by michadn**
This is a PR regarding the issue https://github.com/quicktype/quicktype/issues/2101

The idea is to provide checks for min and max values for integer (int64_t) and number (double). The generated C++ class `ClassMemberConstraints` can look like this after the generation:

```cpp
class ClassMemberConstraints {
        private:
        std::optional<int64_t> min_int_value;
        std::optional<int64_t> max_int_value;
        std::optional<double> min_double_value;
        std::optional<double> max_double_value;
        std::optional<size_t> min_length;
        std::optional<size_t> max_length;
        std::optional<std::string> pattern;

        public:
        ClassMemberConstraints(
            std::optional<int64_t> min_int_value,
            std::optional<int64_t> max_int_value,
            std::optional<double> min_double_value,
            std::optional<double> max_double_value,
            std::optional<size_t> min_length,
            std::optional<size_t> max_length,
            std::optional<std::string> pattern
        ) : min_int_value(min_int_value), max_int_value(max_int_value), min_double_value(min_double_value), max_double_value(max_double_value), min_length(min_length), max_length(max_length), pattern(pattern) {}
        ClassMemberConstraints() = default;
        virtual ~ClassMemberConstraints() = default;

        void set_min_int_value(int64_t min_int_value) { this->min_int_value = min_int_value; }
        auto get_min_int_value() const { return min_int_value; }

        void set_max_int_value(int64_t max_int_value) { this->max_int_value = max_int_value; }
        auto get_max_int_value() const { return max_int_value; }

        void set_min_double_value(double min_double_value) { this->min_double_value = min_double_value; }
        auto get_min_double_value() const { return min_double_value; }

        void set_max_double_value(double max_double_value) { this->max_double_value = max_double_value; }
        auto get_max_double_value() const { return max_double_value; }

        void set_min_length(size_t min_length) { this->min_length = min_length; }
        auto get_min_length() const { return min_length; }

        void set_max_length(size_t max_length) { this->max_length = max_length; }
        auto get_max_length() const { return max_length; }

        void set_pattern(const std::string &  pattern) { this->pattern = pattern; }
        auto get_pattern() const { return pattern; }
    };
```

I also added a test for minimal and maximal values which is using integer instead of number as types in the schema.
I've marked one issue with `TODO`. Maybe someone can help me out?

### CODE REVIEW

**Comment by michadn** [comment]
I've no idea why the DeepSource Analysis fails. Can someone help me?

**Comment by dvdsgl** [comment]
@michadn check here: https://app.deepsource.com/gh/quicktype/quicktype/run/d3fe3d88-b607-455a-8792-89b524885d8f/javascript/

**Comment by michadn** [comment]
@dvdsgl Tanks for your help. Those issues are not related to the changes I've made. Nevertheless I've fixed some of them.
Am I supposed to fix all the issues even if they are not related to my code changes?

**Comment by michadn** [comment]
Because I am not sure how to proceed, I will mark this PR as ready and hope, the DeepSource Analysis failure does not block the PR. Please have a look at my Code changes :)

**Pull request merged**
