### PR TITLE
Separate stuff so as not to have a contagious urijs dep

### PR DESCRIPTION
**Pull request by schani**

### CODE REVIEW

**Comment by dvdsgl** [comment]
Not only does this fix the build, but our bundle sizes have reduced by 40% since `v10`.

**Comment by schani** [comment]
Which changes did that?

**Comment by dvdsgl** [comment]
It would take me a while to figure that out specifically...

**Comment by schani** [comment]
Is it easy to figure out which dependencies we're not including anymore?

**Comment by dvdsgl** [comment]
It looks like quicktype actually grew, but there's a 25% size reduction due to a deduplicated TypeScript import(?).

# v10

image

image

# v12

image

image

**Comment by schani** [comment]
Oh shit, we had the whole of typescript twice??

**Pull request merged**
