### PR TITLE
Support for Charp Text.Json lib from .net 6 using kotlin as example #1347

### PR DESCRIPTION
**Pull request by bzuidgeest**
I have merged the code for System.Text.Json support from @doggy8088 together with the old newtonsoft based generator using the kotlin code as a guideline/template. see #1347 
Changes seem to relatively minor.

~~I'm making this PR to get feedback. I don't think it will be accepted as is as it is lacking test. I don't know how to add those as~~ I am not a typescript/nodejs/npm developer. It's more or less easy enough to read and understand, but that gets one only so far. The normal newtonsoft code still test succesfully using de test docker stuff. ~~Any pointers on needed stuff to add are welcome~~ Most test succeed, I'm still working on about 18, but they might share a failure mode.

p.s. this is my first PR to a public project, be nice :)

### CODE REVIEW

**Comment by Cammin** [comment]
I'd be interested in using this right now, but I have little experience outside my Unity/C# bubble.
Would you be able to tell me how to get this fork setup for myself? I'd really like to be able to generate C# code for System.Text.Json instead of Newtonsoft Json. 🙂

**Comment by DavidBurela** [comment]
Would love to see this one merged.
It is starting to become a blocker, as other frameworks adopt System.Text.Json and ends up with middleware conflicts.

**Comment by dvdsgl** [comment]
@bzuidgeest our CI is fixed and this is running now.

**Comment by dvdsgl** [comment]
@bzuidgeest congratulations and thank you. Thank you @doggy8088 as well.

**Comment by bzuidgeest** [comment]
@dvdsgl Thank you to, it's really nice to know to have been able to add back to a project. Usually I'm just another consumer of code.

**Comment by dvdsgl** [comment]
Cheers @bzuidgeest! You may want to take a look at #2097 next.

**Comment by bzuidgeest** [comment]
> Cheers @bzuidgeest! You may want to take a look at #2097 next.

Already added a comment to that, with an observation

**Pull request merged**
