### PR TITLE
Add date-time support for JavaScript and TypeScript

### PR DESCRIPTION
**Pull request by keitwb**
I tried to mimic the Python implementation where possible.

Related to #316.

### CODE REVIEW

**Comment by keitwb** [comment]
Trying to get the Flow tests passing.  Two "priority" tests, `recursive.json` and `keywords.json` both have `date` fields which are generating `Date` types that are shadowing the global Date object used in my changes.  It seems wrong to disable those tests so I'm trying to figure out the best way to make it work (e.g. use `global/window.Date`) in a way that works for browser and node.js code.  Any suggestions welcome.  I'll hack on it some more tomorrow.

**Comment by keitwb** [comment]
Ok, got it passing, had to skip two tests but I think for good reason.

**Comment by keitwb** [comment]
@schani The CI seems to be stuck on this PR.  Should I have not done a force-push or is it something else?

**Comment by schani** [comment]
@keitwb I don't know what's going on here.  I tried forcing the build on buildkite, but it wants to rebuild the last commit.  Would you mind closing this PR and opening a new one with a different branch name?

**Comment by schani** [comment]
Failure:

```
/app/test/runs/schema-typescript-c12f76/TopLevel.ts:37
  | throw Error(`Invalid value ${JSON.stringify(val)} for type ${JSON.stringify(typ)}`);
  | ^
  | Error: Invalid value "23:20:50.52Z" for type "Date"
  | at invalidValue (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:37:15)
  | at transformDate (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:93:24)
  | at transform (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:126:34)
  | at Object.getOwnPropertyNames.forEach.key (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:106:36)
  | at Array.forEach (<anonymous>)
  | at transformObject (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:103:47)
  | at transform (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:130:57)
  | at cast (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:137:16)
  | at Object.toTopLevel (/app/test/runs/schema-typescript-c12f76/TopLevel.ts:29:16)
  | at Object.<anonymous> (/app/test/runs/schema-typescript-c12f76/main.ts:10:30)
  |  
  | Command failed
  | {
  | "command": "TS_NODE_PROJECT= ts-node main.ts \"/app/test/inputs/schema/date-time.1.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/schema-typescript-c12f76"
  | }
  | Could not run command for JSON output
  | {
  | "error": {
  | "command": "TS_NODE_PROJECT= ts-node main.ts \"/app/test/inputs/schema/date-time.1.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/schema-typescript-c12f76"
  | },
  | "cwd": "/app/test/runs/schema-typescript-c12f76"
  | }
  | Fixture threw an exception
  | {
  | "error": {
  | "error": {
  | "command": "TS_NODE_PROJECT= ts-node main.ts \"/app/test/inputs/schema/date-time.1.json\"",
  | "code": 1,
  | "cwd": "/app/test/runs/schema-typescript-c12f76"
  | },
  | "cwd": "/app/test/runs/schema-typescript-c12f76"
  | },
  | "sample": {
  | "path": "test/inputs/schema/date-time.schema",
  | "additionalRendererOptions": {},
  | "saveOutput": true
  | },
  | "cwd": "/app/test/runs/schema-typescript-c12f76"
  | }
```

You can run these tests locally with `FIXTURE=schema-typescript npm test`

**Comment by keitwb** [comment]
Ok, I got the tests passing with minimal test skipping (only the JSON that has year 0 which ES's Date can't handle).

I assume the "diff" step in BuildKite is expected to fail since this change causes outputs to change?

**Comment by schani** [comment]
Correct, great job!  A cursory look over the diff doesn't reveal any trouble.  In case you want to look at it in detail, [here it is](https://s3.amazonaws.com/quicktype-outputs/diffs/9031a4f4d790756cbe0f1b867f37d77f8c901763-d12dd33551704a5c675f16067049f9b425fbb262.diff).  Let me know if you're happy with it, and I'll merge.

**Comment by schani** [comment]
Thank you! :-)

**Comment by anka-213** [comment]
This is a bit dangerous if you just generate the types and not the validating parsers, since `Date` is not compatible with the actual type `string`.

**Pull request merged**
