### PR TITLE
[NO MERGE] Add urijs types in the distribution

### PR DESCRIPTION
**Pull request by schani**

### CODE REVIEW

**Comment by dvdsgl** [comment]
This feels really hacky.

**Comment by dvdsgl** [comment]
It also does not work. Is there a different approach we can take? We've tried three ways to distribute these stupid types and none has worked.

**Comment by schani** [comment]
Ok, I'll see what happens if I just put the `@types` directory into a repo with a `package.json`.

**Comment by schani** [comment]
This is not it.

**Pull request closed without merging**
