### PR TITLE
[Dart] add required/final props

### PR DESCRIPTION
**Pull request by TarekkMA**
Added 2 new options for Dart language.
* Required constractor parameters (adds @required annotation in the constructor) and importing ```package:meta/meta.dart```
*  Final properties. (Solving #1306)

### CODE REVIEW

**Comment by dvdsgl** [comment]
Great! Can you please drop the changes to package*.json? Thank you.

**Comment by TarekkMA** [comment]
@dvdsgl Oh sorry about that. I have now removed the version change.

**Comment by dvdsgl** [comment]
Thanks!

**Comment by MichaelPriebe** [comment]
Thank you! May you look at the funky int/double situation. An option to use num to make sure you won't have any errors would be helpful.

**Comment by TarekkMA** [comment]
@MichaelPriebe do you mean there is an issue about this PR? Can you give me more info?

**Comment by MichaelPriebe** [comment]
@TarekkMA No, not about this PR, but I get problems if my samples show numbers as int's but when I'm parsing real data I get errors when a double appears in its place. My issue (https://github.com/quicktype/quicktype/issues/1304) was closed because it is a "feature" to be strict, But it takes too much time to go back to my sample and adjust it to show a double. It would be nice to cover all bases with num instead. I figured I would ask you here since you were in the process of making the Dart output better!

**Comment by TarekkMA** [comment]
You should input data with decimal points if you want to have them represented as double. Quicktype can't know if ```{ "d": 1 }```  d should be double or int.  so it assigns it with int type since it has nothing that points to it being double.

Maybe there should be an option to assume all numeric values as a floating-point number, but it's outside the scope of the dart. it should be in the ```quicktype core```

**Comment by MichaelPriebe** [comment]
If there was an option for everything to be [num](https://api.dartlang.org/stable/2.5.2/dart-core/num-class.html) it would cover all bases, but still retain the ability to turn it into a int, or a double.

**Comment by dvdsgl** [comment]
@MichaelPriebe this is off-topic and there is already an issue for  it. Please stop.

**Pull request merged**
