### PR TITLE
Pike: support for JSON top-level primitives. Output code optimizations.

### PR DESCRIPTION
**Pull request by mkrawczuk**

### CODE REVIEW

**Comment by schani** [comment]
This fails tslint (`npm run tslint`):

```
ERROR: /app/src/quicktype-core/language/Pike.ts:278:13 - misplaced 'else'
| ERROR: /app/src/quicktype-core/language/Pike.ts:303:15 - Missing semicolon
```

We use [Prettier](https://prettier.io) for code formatting, which fixes those issues automatically.  There's an extension for VSCode.

**Comment by mkrawczuk** [comment]
Woopsie! Missed that one. Fixups are on the way.

**Comment by mkrawczuk** [comment]
Hmm, weird. I'm running the tests locally and they all pass.

**Comment by schani** [comment]
There was a spurious error, I restarted it.

**Comment by schani** [comment]
[Here are the diffs](https://s3.amazonaws.com/quicktype-outputs/diffs/21681d8d8c0a9b840edba4a39dbf8e76652018b9-1f94e3aaafde087c8a0de593889ca2fe5a68f99b.diff) between the output of `master` and this PR.  Does this look good to you?

**Comment by schani** [comment]
Thank you! :-)

**Pull request merged**
