### PR TITLE
Improved horizontal rule in swift comment syntax

### PR DESCRIPTION
**Pull request by multinerd**
fixed, im closing the previous PR to prevent multiple commits.

### CODE REVIEW

**Comment by multinerd** [comment]
Takes care of issue 628

**Comment by schani** [comment]
@multinerd You can force-push to avoid the multiple commit issue without making a new PR.

**Comment by multinerd** [comment]
like i said, im a git noob :)

lemme know if i need to do anything else

**Comment by dvdsgl** [comment]
I'm just going to squash the PR when we merge. @multinerd you're good!

**Pull request merged**
