### PR TITLE
TypeScript renderer: Option to render unions insted of enums

### PR DESCRIPTION
**Pull request by DexterMsft**
Reverted constructor changes and rebased onto master

### CODE REVIEW

**Comment by DexterMicrosoft** [comment]
Hi @schani!
This is a change corresponding to PR #1789, I have removed the changes from the constructor and rebased onto master, do you think you could merge it onto master?
Thank you!

**Comment by DexterMsft** [comment]
Would really love to get this into the repo as it would help a lot in our project and I'm guessing it would help a lot of other people that use QuickType @schani

**Comment by DexterMsft** [comment]
Quick ping to see if we could get this fix reviewed @schani

**Comment by DexterMsft** [comment]
Thank you for reviewing it @schani!

Any idea when will the npm package be updated with this change?

**Comment by schani** [comment]
Done.

**Comment by DexterMsft** [comment]
Awesome, thank you so much @schani  and @zewish!

**Pull request merged**
