### PR TITLE
add php support

### PR DESCRIPTION
**Pull request by mabels**
I built for me working php language adapter.
There a still some thing todo like Date/Time/UUID Type support.
But I hope it's a nice starting point. To the php language support.

cheers

meno

### CODE REVIEW

**Comment by schani** [comment]
@mabels Thank you so much!  Would you mind rebasing your PR onto the latest `master`?  The one you were working on unfortunately doesn't build anymore, but it got fixed in the mean time.

**Comment by mabels** [comment]
I will rebase it, again.

Meno

**Comment by mabels** [comment]
Hi,

i just updated all so the php stuff is ready for rebase on your side.
TODO: add php to your test enviroment:
```
require_once("./doof.php");

$json1 = json_encode(Purchase::sample()->to());
$json2 = json_encode(Purchase::from(json_decode($json1))->to());

if ($json1 == $json2) {
  echo "all good";
} else {
  echo($json1);
  echo($json2);
}
```

**Comment by schani** [comment]
@mabels I added test fixture for PHP here (I couldn't push to your branch, so had to make an independent PR, but feel free to just take whatever you want from there and I'll close mine again): https://github.com/quicktype/quicktype/pull/1616

Unfortunately almost all tests fail.  I don't know any PHP, so I have no idea whether it's because of my PHP setup, or because the generated code is incorrect, or some other reason.  You can run the tests with

`npm run build && FIXTURE=php npm run test`

**Comment by mabels** [comment]
Hi,
i stepped yesterday in the tests of quicktype and discovered there are
"some" things to do.
I will continue the php work in the next days.

sorry

meno

**Comment by schani** [comment]
Thank you so much!

**Comment by schani** [comment]
@mabels We got three type check errors:

```
ERROR: /app/src/quicktype-core/language/Php.ts:795:17 - This type is not allowed in the condition because it could be undefined. Only booleans are allowed.
  | ERROR: /app/src/quicktype-core/language/Php.ts:797:17 - This type is not allowed in the 'if' condition because it could be undefined. Only booleans are allowed.
  | ERROR: /app/src/quicktype-core/language/Php.ts:894:21 - This type is not allowed in the 'if' condition because it could be undefined. Only booleans are allowed.
```

**Comment by schani** [comment]
@mabels Any news on this?

**Comment by mabels** [comment]
i'm still fighting with all tests. There are some issues with currently
with union's.
I'm just got back to work today and will hopefully find some time this week

cheers

meno

**Comment by schani** [comment]
Can I help with anything?

**Comment by rvanlaak** [comment]
Should the work done by @schani in https://github.com/quicktype/quicktype/pull/1616 be merged in this PR?

**Comment by alexsandro-xpt** [comment]
Any progress? What's up?

**Comment by dvdsgl** [comment]
Superseded by #1616

**Pull request closed without merging**
