### PR TITLE
Use the module name as the C# namespace

### PR DESCRIPTION
**Pull request by schani**

### CODE REVIEW

**Comment by schani** [comment]
I forgot we have this module name thing.  That would allow us to have a global option for module/namespace name, instead of it being language-specific.

**Comment by schani** [comment]
@dvdsgl are you ok with merging this?

**Comment by dvdsgl** [comment]
I found that sometimes there are issues with the namespace and top-level class have the same name.

**Comment by schani** [comment]
Then shouldn't we rename the namespace if the user wants the toplevel to be called `QuickType`?

**Comment by schani** [comment]
We use an option for this now.

**Pull request closed without merging**
