### PR TITLE
Trying to enable TypeScript strict null checks

### PR DESCRIPTION
**Pull request by schani**
I fixed all our code to work with strict null checks
(might have caught one or two unproblematic bugs),
but I don't know how to configure it such that only
our code, and not imported modules, are compiled
with strict null checks.  At least one module doesn't
compile.

### CODE REVIEW

**Comment by schani** [comment]
@dvdsgl If you know how to enable strict null checks just for our code, that would be really nice.

**Comment by dvdsgl** [comment]
I enabled `strictNullChecks` in `cli/tsconfig.json` and was able to build without error. How did you build with errors?

**Comment by schani** [comment]
I don't know, I'll try again ;-)

**Comment by schani** [comment]
Yeah, weird, works for me, too.

**Comment by schani** [comment]
@dvdsgl Shall we merge this?

**Pull request merged**
