### PR TITLE
Julia Support

### PR DESCRIPTION
**Pull request by kskyten**
This should work for basic conversions. Unions, Enums, Nullables and escaping strings are not properly supported yet.

I cobbled this together based on the Rust and Python translators. I could really use some help from someone who knows TypeScript. For example, I get an error when I try to build the project with "npm run build":

```bash
src/quicktype-core/language/Julia.ts(129,26): error TS6138: Property '_options' is declared but its value is never read.
src/quicktype-core/language/Julia.ts(242,75): error TS6133: 'prop' is declared but its value is never read.
src/quicktype-core/language/Julia.ts(251,26): error TS6133: 'c' is declared but its value is never read.
src/quicktype-core/language/Julia.ts(291,25): error TS6133: 'u' is declared but its value is never read.
src/quicktype-core/language/Julia.ts(291,39): error TS6133: 'unionName' is declared but its value is never read.
src/quicktype-core/language/Julia.ts(316,56): error TS6133: 'jsonName' is declared but its value is never read.
src/quicktype-core/language/Julia.ts(339,15): error TS6133: 'topLevelName' is declared but its value is never read.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! quicktype@15.0.0 build: `script/build.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the quicktype@15.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2021-01-06T18_09_04_691Z-debug.log
```

Enums are a bit tricky in Julia at the moment since you can not reuse enum members in a different enum (https://discourse.julialang.org/t/cannot-reuse-enum-member-in-different-enum/21342). How do I add an option for disabling enums in Quicktype? Also, what is the easiest way to check if a dictionary requires renames (ie. how do I implement the `hasRenames` method)? I'm not sure I got the string escaping right either. Julia uses the dollar sign for string interpolation. What does `canBeForwardDeclared` do?

### CODE REVIEW

**Comment by kskyten** [comment]
Also, how do I add the test dependencies? The tests need Julia with the `JSON3`, `StructTypes` and `Nullables` packages.

**Comment by schani** [comment]
@kskyten Thank you so much for your contribution!

There are a few lint issues, but they're easy to fix:

```
commit c5e1169e86dc9b33e938149740324d4c4fae10d7
Author: Mark Probst <mark.probst@gmail.com>
Date:   Sun Jan 10 18:38:58 2021 -0500

    Fix a few lint issues

diff --git a/src/quicktype-core/language/Julia.ts b/src/quicktype-core/language/Julia.ts
index 1ae025e2..ce9fdb33 100644
--- a/src/quicktype-core/language/Julia.ts
+++ b/src/quicktype-core/language/Julia.ts
@@ -14,7 +14,8 @@ import {
     isPrintable,
     isAscii,
     isLetterOrUnderscore,
-    standardUnicodeHexEscape} from "../support/Strings";
+    standardUnicodeHexEscape
+} from "../support/Strings";
 import { Name, Namer, funPrefixNamer } from "../Naming";
 import { UnionType, Type, ClassType, EnumType } from "../Type";
 import { matchType, nullableFromUnion, removeNullFromUnion } from "../TypeUtils";
@@ -29,9 +30,11 @@ export const juliaOptions = {};
 
 export class JuliaTargetLanguage extends TargetLanguage {
     protected makeRenderer(renderContext: RenderContext, _untypedOptionValues: { [name: string]: any }): JuliaRenderer {
-        return new JuliaRenderer(this, renderContext,
-                            // getOptionValues(juliaOptions, untypedOptionValues)
-                           );
+        return new JuliaRenderer(
+            this,
+            renderContext
+            // getOptionValues(juliaOptions, untypedOptionValues)
+        );
     }
 
     constructor() {
@@ -114,10 +117,9 @@ function juliaStyle(original: string, isSnakeCase: boolean): string {
 const snakeNamingFunction = funPrefixNamer("default", (original: string) => juliaStyle(original, true));
 const camelNamingFunction = funPrefixNamer("camel", (original: string) => juliaStyle(original, false));
 
-
 const standardUnicodeJuliaEscape = (codePoint: number): string => {
-    if (codePoint == 0x24) {
-        return "\\$"
+    if (codePoint === 0x24) {
+        return "\\$";
     } else {
         return standardUnicodeHexEscape(codePoint);
     }
@@ -128,7 +130,7 @@ const juliaStringEscape = utf32ConcatMap(escapeNonPrintableMapper(isPrintable, s
 export class JuliaRenderer extends ConvenienceRenderer {
     constructor(
         targetLanguage: TargetLanguage,
-        renderContext: RenderContext,
+        renderContext: RenderContext
         // private readonly _options: OptionValues<typeof juliaOptions>
     ) {
         super(targetLanguage, renderContext);
@@ -232,22 +234,21 @@ export class JuliaRenderer extends ConvenienceRenderer {
         const escapedName = juliaStringEscape(jsonName);
         const namesDiffer = this.sourcelikeToString(propName) !== escapedName;
         if (namesDiffer) {
-            this.emitLine("(:", this.sourcelikeToString(propName), ", Symbol(raw\"", escapedName, "\")),");
+            this.emitLine("(:", this.sourcelikeToString(propName), ', Symbol(raw"', escapedName, '")),');
         }
     }
 
     protected emitNameTranslation(c: ClassType, className: Name): void {
-        const blankLines = "none"
+        const blankLines = "none";
         const self = this;
-        this.emitLine("StructTypes.names(::Type{", className, "}) = (")
-        this.indent(
-            function(){
-                self.forEachClassProperty(c, blankLines, (name, jsonName, _prop) => {
+        this.emitLine("StructTypes.names(::Type{", className, "}) = (");
+        this.indent(function () {
+            self.forEachClassProperty(c, blankLines, (name, jsonName, _prop) => {
                 // self.emitDescription(self.descriptionForClassProperty(c, jsonName));
                 self.emitRenameAttribute(name, jsonName);
-                });
             });
-        this.emitLine(")")
+        });
+        this.emitLine(")");
     }
 
     // TODO
@@ -264,9 +265,9 @@ export class JuliaRenderer extends ConvenienceRenderer {
     protected emitStructDefinition(c: ClassType, className: Name): void {
         this.emitDescription(this.descriptionForType(c));
 
-        const blankLines = "none"
+        const blankLines = "none";
         const self = this;
-        const structBody = function(){
+        const structBody = function () {
             self.forEachClassProperty(c, blankLines, (name, jsonName, prop) => {
                 self.emitDescription(self.descriptionForClassProperty(c, jsonName));
                 self.emitLine(name, " :: ", self.breakCycle(prop.type, true));
@@ -293,14 +294,11 @@ export class JuliaRenderer extends ConvenienceRenderer {
     // TODO
     protected emitUnion(_u: UnionType, _unionName: Name): void {
         // const isMaybeWithSingleType = nullableFromUnion(u);
-
         // if (isMaybeWithSingleType !== null) {
         //     return;
         // }
-
         // this.emitDescription(this.descriptionForType(u));
         // const [, nonNulls] = removeNullFromUnion(u);
-
         // const blankLines = this._options.density === Density.Dense ? "none" : "interposing";
         // this.emitBlock(["pub enum ", unionName], () =>
         //     this.forEachUnionMember(u, nonNulls, blankLines, null, (fieldName, t) => {
@@ -314,7 +312,7 @@ export class JuliaRenderer extends ConvenienceRenderer {
     protected emitEnumDefinition(e: EnumType, enumName: Name): void {
         this.emitDescription(this.descriptionForType(e));
 
-        const blankLines = "none"
+        const blankLines = "none";
         this.emitBlock(["@option ", enumName, " begin"], () =>
             this.forEachEnumCase(e, blankLines, (name, _jsonName) => {
                 // this.emitRenameAttribute(name, jsonName);
@@ -364,6 +362,5 @@ export class JuliaRenderer extends ConvenienceRenderer {
             (t, name) => this.emitTopLevelAlias(t, name),
             t => this.namedTypeToNameForTopLevel(t) === undefined
         );
-
     }
 }
```

As for your questions:

* You have to handle enums some way or another, potentially just by treating them as strings.  Take a look at how Go, Objective-C, or Javascript handle them, to give you some options.
* The testing dependencies go into `Dockerfile`.  If you have the tests working in your environment I'm happy to help with the Docker stuff.
* Sorry, I don't know what `hasRenames` is supposed to do.  Could you explain?
* String escaping looks correct.  Dart does the same thing in a different way.
* `canBeForwardDeclared` works in conjunction with `needsTypeDeclarationBeforeUse` to support languages that need declarations before use.  quicktype will try to reorder the types so forward declarations are not needed, but when they are, you'll get a `decl.kind === "forward"`.  I see you're already handling that, it seems.

**Comment by kskyten** [comment]
Currently, it generates code for renaming the properties whether they need to be renamed or not. For example, running
```bash
echo '{"name": "Bob"}' | script/quicktype -l julia 
```
outputs
```julia
# Example code that deserializes and serializes an object of type "MyType" from a string.
# using JSON3
# JSON3.read(str::String, MyType)
# JSON3.write(obj)

using JSON3
using StructTypes
using Nullables

mutable struct TopLevel
    name :: String

    TopLevel() = new()
end
StructTypes.StructType(::Type{TopLevel}) = StructTypes.Mutable()

StructTypes.names(::Type{TopLevel}) = (
)
```
The last two lines are not needed. `hasRenames` should be a boolean function that checks whether there are properties that shuold be renamed.

**Comment by schani** [comment]
I see.  I think your best shot at implementing this is actually to change the code to something like this (this is not tested):

```
    private makeRename(propName: Name, jsonName: string): [string, string] | undefined {
        const propNameString = this.sourcelikeToString(propName);
        const escapedName = juliaStringEscape(jsonName);
        if (escapedName === propNameString) return undefined;
        return [propNameString, escapedName];
    }

    protected emitNameTranslation(c: ClassType, className: Name): void {
        const renames: [string, string][] = [];
        this.forEachClassProperty(c, "none", (name, jsonName, _prop) => {
            const rename = this.makeRename(name, jsonName);
            if (rename !== undefined) {
                renames.push(rename);
            }
        });
        if (renames.length === 0) return;
        this.emitLine("StructTypes.names(::Type{", className, "}) = (");
        this.indent(() => {
            for (const [propNameString, escapedName] of renames) {
                this.emitLine("(:", propNameString, ', Symbol(raw"', escapedName, '")),');
            }
        });
        this.emitLine(")");
    }
```

Then you don't need `hasRenames` anymore.

**Comment by schani** [comment]
@kskyten Can I help?

**Comment by dvdsgl** [comment]
Please reopen if you plan to take another crack at this. Thanks!

**Pull request closed without merging**
