### PR TITLE
Upgrade Elm to 0.19.1

### LINKED ISSUE #1165: Is Elm 0.19 and latest Json.Decode.Pipeline supported?
I got a few compilation errors using Elm 0.19, and I'm not sure if this is just me or what Elm and `Json.Decode.Pipeline` package version is currently supported?

Would be nice to have that specifically mentioned somewhere.

If I have time I'll try and figure out what changes are required for Elm 0.19 support...

### PR DESCRIPTION
**Pull request by icidasset**
Fixes #1165
Continuation of #1219 (thanks @jonathanjouty!)

Changes besides the Elm 0.19 changes:
- I tried to remove as much named function arguments as possible as to avoid name collisions, and used function composition where needed/possible.
- Removed 2 helpers from the generated code, as the new `elm/json` library makes things easier
- I moved a lot of pieces in the `src/quicktype-core/language/Elm.ts` to group things up a bit.

PS. My coding style is quite different from what it was before, so let me know if I need to run that code through a formatter or something like that.

### CODE REVIEW

**Comment by schani** [comment]
@icidasset Thank you for your contribution!

You reformatted the whole `Elm.ts` file, which makes the PR not only very hard to review, but the new format also fails our linting rules.  See the build output.  Examples:

```
ERROR: /app/src/quicktype-core/language/Elm.ts:11:60 - Missing semicolon
  | ERROR: /app/src/quicktype-core/language/Elm.ts:13:1 - Consecutive blank lines are forbidden
```

**Comment by icidasset** [comment]
> @icidasset Thank you for your contribution!
> 
> You reformatted the whole `Elm.ts` file, which makes the PR not only very hard to review, but the new format also fails our linting rules. See the build output. Examples:
> 
> ```
> ERROR: /app/src/quicktype-core/language/Elm.ts:11:60 - Missing semicolon
>   | ERROR: /app/src/quicktype-core/language/Elm.ts:13:1 - Consecutive blank lines are forbidden
> ```

Yes for sure, hence my earlier formatter comment.
I've ran it through `prettier` and made sure the linting succeeded.
Is it better now? Or do I need to adjust anything else?

**Comment by schani** [comment]
Thank you for fixing the formatting! :-)

The test suite fails now:

```
Dependencies ready!
  | Compiling (2)
  |  
  | -- ERROR -----------------------------------------------------------------------
  |  
  | I ran into something that bypassed the normal error reporting process! I
  | extracted whatever information I could from the internal error:
  |  
  | >   /app/test/runs/schema-elm-62cd20/elm-stuff/0.19.1/d.dat: openBinaryFile: resource busy (file is locked)
  |  
  | These errors are usually pretty confusing, so start by asking around on one of
  | forums listed at https://elm-lang.org/community to see if anyone can get you
  | unstuck quickly.
  |  
  | -- REQUEST ---------------------------------------------------------------------
  |  
  | If you are feeling up to it, please try to get your code down to the smallest
  | version that still triggers this message. Ideally in a single Main.elm and
  | elm.json file.
  |  
  | From there open a NEW issue at https://github.com/elm/compiler/issues with your
  | reduced example pasted in directly. (Not a link to a repo or gist!) Do not worry
  | about if someone else saw something similar. More examples is better!
  |  
  | This kind of error is usually tied up in larger architectural choices that are
  | hard to change, so even when we have a couple good examples, it can take some
  | time to resolve in a solid way.elm: /app/test/runs/schema-elm-62cd20/elm-stuff/0.19.1/d.dat: openBinaryFile: resource busy (file is locked)
  |  
  | Fixture threw an exception
  | {
  | "error": {
  | "command": "sysconfcpus -n 1 elm make Main.elm --output elm.js",
  | "code": 1
  | },
  | "sample": {
  | "path": "test/inputs/schema/class-map-union.schema",
  | "additionalRendererOptions": {},
  | "saveOutput": true
  | },
  | "cwd": "/app/test/runs/schema-elm-62cd20"
  | }
  | [object Object]
  | at /app/test/test.ts:68:17
  | at step (/app/test/test.ts:32:23)
  | at Object.throw (/app/test/test.ts:13:53)
  | at rejected (/app/test/test.ts:5:65)
  | at <anonymous>
  | at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  | npm ERR! Test failed.  See above for more details.
```

**Comment by icidasset** [comment]
@schani Looking into it, not sure why this is only happening on this CI. And now the Dart tests are failing randomly, can I restart the tests somehow?

**Comment by schani** [comment]
I'm trying to figure out what's going on with Dart.

**Comment by schani** [comment]
#1669 fixes the Dart issue.  Could you rebase on `master`?

**Comment by icidasset** [comment]
@schani That fixed it, thanks! The elm tests now run successfully 👍

**Comment by icidasset** [comment]
@schani Rebased again. All tests are passing, except the diff thing again, not sure what that's about.

**Comment by icidasset** [comment]
Any chance of getting this merged?

**Comment by jhult** [comment]
@schani, any news on getting this merged?

**Review by esfomeado — APPROVED** [review]

**Comment by schani** [comment]
This fails tests:

```
quicktype threw an exception
  | {
  | "error": {
  | "errorMessage": "Internal error: ${message}",
  | "messageName": "InternalError",
  | "properties": {
  | "message": "Defined value expected, but got undefined"
  | }
  | },
  | "languageName": "elm",
  | "sourceFile": "/app/test/inputs/json/priority/bug855-short.json",
  | "sourceLanguage": "json",
  | "additionalRendererOptions": {},
  | "cwd": "/app/test/runs/elm-118d42"
  | }
  | [object Object]
  | at /app/test/test.ts:68:17
  | at step (/app/test/test.ts:32:23)
  | at Object.throw (/app/test/test.ts:13:53)
  | at rejected (/app/test/test.ts:5:65)
  | at <anonymous>
  | at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  | npm ERR! Test failed.  See above for more details.
 
```

**Comment by icidasset** [comment]
Hmm, I can't figure out what's wrong, the tests aren't telling me anything.
I've been using this fork in production for months and everything seems to work fine.

**Comment by dvdsgl** [comment]
@icidasset Our CI has been revamped and the Elm fixture is enabled in this PR. Unfortunately the tests fail immediately, in case you can take a look. I'd love to get this merged!

**Comment by dvdsgl** [comment]
Please reopen if you plan to take another crack at this. Thanks!

**Comment by icidasset** [comment]
@dvdsgl Thanks for taking another look at this. I'm afraid I don't immediately know what the issue is. I guess quite a few things have changed over the past 3 years regarding how a quicktype integration should be written? I might come back to this once I have some more free time.

**Comment by dvdsgl** [comment]
We've moved files around but the SDK is basically identical. Shouldn't be too tricky. I'll help you with the CI pieces if you pick it back up.

**Pull request closed without merging**
