### PR TITLE
Add edition 2018 style use sedre rather than extern crate

### LINKED ISSUE #1493: Use of serde instead of serde_json
https://github.com/quicktype/quicktype/blob/7a6a0fbdaa817ac36d0acf8701fe92e36ae261d6/src/quicktype-core/language/Rust.ts#L378
Think this line might be outdated. I changed it to `use serde::{Deserialize, Serialize};` in my own code.

### PR DESCRIPTION
**Pull request by mocsy**
Closes #1493 and #1210

### CODE REVIEW

**Comment by schani** [comment]
Thank you so much!

**Comment by Snazzie** [comment]
How do we specifiy this in cli?

**Comment by mocsy** [comment]
```
echo '{ "name": "David" }' | quicktype -l rust --derive-debug --edition-2018 --leading-comments
```
Would be the right answer.

Doing `npm i -g quicktype` doesn't work for me either and master also doesn't seem to build on my machine atm.

**Comment by Snazzie** [comment]
yeah, i tried that at first but i get `Error: Option parsing failed: Unknown option: --edition-2018` :P

**Pull request merged**
