### PR TITLE
feat: Add support for json_annotation in Dart

### PR DESCRIPTION
**Pull request by hm-tamim**
[json_annotation](https://pub.dev/packages/json_annotation) is a very popular Dart package that provides annotations and code generation capabilities for JSON serialization and deserialization by [json_serializable](https://pub.dev/packages/json_serializable)

I hope it would be very useful addition for Flutter community. Please add this option to the website as well, and let me know if any changes are required.

### CODE REVIEW

**Comment by hm-tamim** [comment]
Hi @dvdsgl Is it possible to check this PR?

**Comment by dvdsgl** [comment]
Thanks! Let me just fix the tests...

**Comment by hm-tamim** [comment]
Can't see tests for Dart, for example Freezed, Hive etc.

**Comment by hm-tamim** [comment]
Hi @dvdsgl

**Comment by Habnarm1** [comment]
Merge thus we need it

**Comment by hm-tamim** [comment]
Thanks for merging @dvdsgl When can we expect this to go live in website?

**Comment by Habnarm1** [comment]
Yes please push live, we really need it, it would help save a lot of time,

**Pull request merged**
