### PR TITLE
Swift in typescript

### PR DESCRIPTION
**Pull request by schani**
This leaves us with Swift 3 in PureScript and Swift 4 in TypeScript.

### CODE REVIEW

**Comment by schani** [comment]
@dvdsgl How do you feel about this? We'd have two separate Swift languages with this PR, as opposed to one with an option.  Or should we just get rid of Swift 3 right away?

**Comment by dvdsgl** [comment]
I'm fine if you remove Swift 3 entirely, but could you just jerryrig the PureScript renderer into the TypeScript renderer by calling the PureScript renderer?

**Comment by schani** [comment]
That depends on how long we want to keep it around.  Here's a proposal:

1. Make a target language wrapper for Swift that uses either PS Swift or TS Swift, depending on the option passed.

2. Make PS target languages report an error when trying to generate code for an enum.

3. Implement enums in TS Swift.

4. Ship TS Swift and enums.

At that point we'd have enums in all TS renderers, and we'd fail with an error for PS renderers when enums are used.  That's not a big deal (yet), because enums can only can from JSON Schema.  I wouldn't talk much about the feature at that point.

Once we implement inferring enums and/or GraphQL we should move away completely from PS renderers, because those are high(er) profile features and I think we should support them on all target languages.

**Comment by dvdsgl** [comment]
Let's just drop Swift 3 and reconsider if we hear anyone ask about it. Sounds like a lot of effort if we only have a handful of Swift 3 users, and they can always stick with an older version of quicktype.

**Comment by schani** [comment]
That still leaves us with Elm and Java not supporting enums yet, and I don't have the motivation to port them to TS at this point, so really the only additional effort my proposal entails is the target language wrapper, which should be pretty trivial.

**Comment by schani** [comment]
Basically, the options are:

1. Port the last two PS renderers to TS.  I don't have the motivation to do this right now, so you'll have to do it, soon.

2. Keep the PS renderers around until we have either GraphQL or enum inference, at which point my motivation to port renderers will probably be sufficient to do it.  In this case it costs us very little to keep Swift 3.

**Comment by schani** [comment]
@dvdsgl If the checks pass I think this is ready to merge. Let me know if you have any objections.

**Pull request merged**
