### PR TITLE
PHP Support

### PR DESCRIPTION
**Pull request by schani**

### CODE REVIEW

**Comment by Naoero** [comment]
Hello, I wanted to know what is the status of this merge request?

**Comment by rvanlaak** [comment]
Although some tests are failing, @schani would this PR be ready for review?

**Comment by ThaDaVos** [comment]
Any progress on this? Have used the VSCode extension a lot for Typescript but now also need to use it for PHP too

**Comment by alexsandro-xpt** [comment]
Some news about this PR?

**Review by matronator — APPROVED** [review]

**Comment by rvanlaak** [comment]
When you are looking for PHP models, it might be best to then also use a schema generator written in PHP. Maybe the solution would be to start using https://github.com/api-platform/schema-generator instead?

**Comment by dvdsgl** [comment]
@mabels this is all up-to-date with working test harness in CI -- can you take a look?

**Comment by rvanlaak** [comment]
Awesome! Planning on tagging v7.1 soon? Or will you do more polishing and introduce BC breaks as well?

Also saw that the PHP target was not mentioned at the Readme yet.

**Comment by dvdsgl** [comment]
@rvanlaak want to make a PR? I just got out CI back online and did the bare minimum to accept outstanding PRs with tests. If you'd like to PR the README, I'd much appreciate it :D

**Pull request merged**
